services:
  frontend:
    build: ./blog-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./blog-backend
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend